# Generated by Django 2.2.1 on 2019-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhakasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
