# Generated by Django 2.2.1 on 2019-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhakasApp', '0002_auto_20190731_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.TextField(),
        ),
    ]
