# Generated by Django 2.2.1 on 2019-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhakasApp', '0003_auto_20190731_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
