# Generated by Django 2.2.1 on 2019-07-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhakasApp', '0005_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
